//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuWeatherService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string LocationKey { get; set; }
        public string Place { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
    }
}
